import type { Metadata } from 'next';
import '@mantine/core/styles.css';
import '@/styles/globals.css';
import ThemeProvider from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-screen overflow-y-hidden">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
